import type { CodeyBlockDefinition } from "./types";

export const actionBlocks: CodeyBlockDefinition[] = [
  {
    type: "rocky_forward_for",
    message0: "%{BKY_1BOT_CODEY_ACTION_FORWARD_FOR}",
    args0: [
      { type: "field_number", name: "POWER", value: 50, min: -100, max: 100, precision: 1 },
      { type: "field_number", name: "SECONDS", value: 1, min: 0, precision: 0.1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_FORWARD_FOR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_backward_for",
    message0: "%{BKY_1BOT_CODEY_ACTION_BACKWARD_FOR}",
    args0: [
      { type: "field_number", name: "POWER", value: 50, min: -100, max: 100, precision: 1 },
      { type: "field_number", name: "SECONDS", value: 1, min: 0, precision: 0.1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_BACKWARD_FOR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_turn_left_for",
    message0: "%{BKY_1BOT_CODEY_ACTION_TURN_LEFT_FOR}",
    args0: [
      { type: "field_number", name: "POWER", value: 50, min: -100, max: 100, precision: 1 },
      { type: "field_number", name: "SECONDS", value: 1, min: 0, precision: 0.1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_TURN_LEFT_FOR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_turn_right_for",
    message0: "%{BKY_1BOT_CODEY_ACTION_TURN_RIGHT_FOR}",
    args0: [
      { type: "field_number", name: "POWER", value: 50, min: -100, max: 100, precision: 1 },
      { type: "field_number", name: "SECONDS", value: 1, min: 0, precision: 0.1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_TURN_RIGHT_FOR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_forward_straight_for",
    message0: "%{BKY_1BOT_CODEY_ACTION_FORWARD_STRAIGHT_FOR}",
    args0: [
      { type: "field_number", name: "POWER", value: 50, min: -100, max: 100, precision: 1 },
      { type: "field_number", name: "SECONDS", value: 1, min: 0, precision: 0.1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_FORWARD_STRAIGHT_FOR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_backward_straight_for",
    message0: "%{BKY_1BOT_CODEY_ACTION_BACKWARD_STRAIGHT_FOR}",
    args0: [
      { type: "field_number", name: "POWER", value: 50, min: -100, max: 100, precision: 1 },
      { type: "field_number", name: "SECONDS", value: 1, min: 0, precision: 0.1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_BACKWARD_STRAIGHT_FOR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_turn_left_degree",
    message0: "%{BKY_1BOT_CODEY_ACTION_TURN_LEFT_DEGREE}",
    args0: [{ type: "field_number", name: "ANGLE", value: 15, min: 0, precision: 1 }],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_TURN_LEFT_DEGREE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_turn_right_degree",
    message0: "%{BKY_1BOT_CODEY_ACTION_TURN_RIGHT_DEGREE}",
    args0: [{ type: "field_number", name: "ANGLE", value: 15, min: 0, precision: 1 }],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_TURN_RIGHT_DEGREE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_move_power",
    message0: "%{BKY_1BOT_CODEY_ACTION_MOVE_POWER}",
    args0: [
      {
        type: "field_dropdown",
        name: "DIRECTION",
        options: [
          ["%{BKY_1BOT_CODEY_ACTION_FORWARD}", "forward"],
          ["%{BKY_1BOT_CODEY_ACTION_BACKWARD}", "backward"],
          ["%{BKY_1BOT_CODEY_ACTION_LEFT}", "turn_left"],
          ["%{BKY_1BOT_CODEY_ACTION_RIGHT}", "turn_right"],
        ],
      },
      { type: "field_number", name: "POWER", value: 50, min: -100, max: 100, precision: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_MOVE_POWER_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_drive_power",
    message0: "%{BKY_1BOT_CODEY_ACTION_DRIVE_POWER}",
    args0: [
      { type: "field_number", name: "LEFT_POWER", value: 50, min: -100, max: 100, precision: 1 },
      { type: "field_number", name: "RIGHT_POWER", value: 50, min: -100, max: 100, precision: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_DRIVE_POWER_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_stop",
    message0: "%{BKY_1BOT_CODEY_ACTION_STOP}",
    previousStatement: null,
    nextStatement: null,
    colour: "#4C8EF7",
    tooltip: "%{BKY_1BOT_CODEY_ACTION_STOP_TOOLTIP}",
    helpUrl: "",
  },
];
