import { codeyImageOptions } from "./options";
import type { CodeyBlockDefinition } from "./types";

export const appearanceBlocks: CodeyBlockDefinition[] = [
  {
    type: "codey_show_image",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_IMAGE}",
    args0: [{ type: "field_dropdown", name: "IMAGE", options: codeyImageOptions }],
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_IMAGE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_show_image_at",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_IMAGE_AT}",
    args0: [
      { type: "field_dropdown", name: "IMAGE", options: codeyImageOptions },
      { type: "field_number", name: "X", value: 0, min: -15, max: 15, precision: 1 },
      { type: "field_number", name: "Y", value: 0, min: -7, max: 7, precision: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_IMAGE_AT_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_clear_display",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_CLEAR}",
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_CLEAR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_show_text",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_TEXT}",
    args0: [{ type: "field_input", name: "TEXT", text: "hello" }],
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_TEXT_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_show_text_until_done",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_TEXT_UNTIL_DONE}",
    args0: [{ type: "field_input", name: "TEXT", text: "hello" }],
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_TEXT_UNTIL_DONE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_show_text_at",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_TEXT_AT}",
    args0: [
      { type: "field_input", name: "TEXT", text: "hello" },
      { type: "field_number", name: "X", value: 0, min: -15, max: 15, precision: 1 },
      { type: "field_number", name: "Y", value: 0, min: -7, max: 7, precision: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_SHOW_TEXT_AT_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_set_pixel_on",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_PIXEL_ON}",
    args0: [
      { type: "field_number", name: "X", value: 0, min: 0, max: 15, precision: 1 },
      { type: "field_number", name: "Y", value: 0, min: 0, max: 7, precision: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_PIXEL_ON_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_set_pixel_off",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_PIXEL_OFF}",
    args0: [
      { type: "field_number", name: "X", value: 0, min: 0, max: 15, precision: 1 },
      { type: "field_number", name: "Y", value: 0, min: 0, max: 7, precision: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_PIXEL_OFF_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_toggle_pixel",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_PIXEL_TOGGLE}",
    args0: [
      { type: "field_number", name: "X", value: 0, min: 0, max: 15, precision: 1 },
      { type: "field_number", name: "Y", value: 0, min: 0, max: 7, precision: 1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_PIXEL_TOGGLE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_get_pixel",
    message0: "%{BKY_1BOT_CODEY_APPEARANCE_PIXEL_GET}",
    args0: [
      { type: "field_number", name: "X", value: 0, min: 0, max: 15, precision: 1 },
      { type: "field_number", name: "Y", value: 0, min: 0, max: 7, precision: 1 },
    ],
    output: "Boolean",
    colour: "#8B5CF6",
    tooltip: "%{BKY_1BOT_CODEY_APPEARANCE_PIXEL_GET_TOOLTIP}",
    helpUrl: "",
  },
];
