import type { CodeyBlockDefinition } from "./types";

export const sensorBlocks: CodeyBlockDefinition[] = [
  {
    type: "codey_potentiometer_value",
    message0: "%{BKY_1BOT_CODEY_SENSOR_POTENTIOMETER}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_POTENTIOMETER_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_volume",
    message0: "%{BKY_1BOT_CODEY_SENSOR_VOLUME}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_VOLUME_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_light_intensity",
    message0: "%{BKY_1BOT_CODEY_SENSOR_LIGHT}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_LIGHT_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_battery_level",
    message0: "%{BKY_1BOT_CODEY_SENSOR_BATTERY}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_BATTERY_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_is_shaked",
    message0: "%{BKY_1BOT_CODEY_SENSOR_IS_SHAKED}",
    output: "Boolean",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_IS_SHAKED_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_shake_strength",
    message0: "%{BKY_1BOT_CODEY_SENSOR_SHAKE_STRENGTH}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_SHAKE_STRENGTH_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_is_tilted",
    message0: "%{BKY_1BOT_CODEY_SENSOR_IS_TILTED}",
    args0: [
      {
        type: "field_dropdown",
        name: "DIRECTION",
        options: [
          ["%{BKY_1BOT_CODEY_SENSOR_LEFT}", "LEFT"],
          ["%{BKY_1BOT_CODEY_SENSOR_RIGHT}", "RIGHT"],
        ],
      },
    ],
    output: "Boolean",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_IS_TILTED_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_is_face",
    message0: "%{BKY_1BOT_CODEY_SENSOR_IS_FACE}",
    args0: [
      {
        type: "field_dropdown",
        name: "FACE",
        options: [
          ["%{BKY_1BOT_CODEY_SENSOR_FACE_UP}", "DISPLAY_UP"],
          ["%{BKY_1BOT_CODEY_SENSOR_FACE_DOWN}", "DISPLAY_DOWN"],
          ["%{BKY_1BOT_CODEY_SENSOR_EARS_UP}", "EARS_UP"],
          ["%{BKY_1BOT_CODEY_SENSOR_EARS_DOWN}", "EARS_DOWN"],
          ["%{BKY_1BOT_CODEY_SENSOR_UPRIGHT}", "UPRIGHT"],
        ],
      },
    ],
    output: "Boolean",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_IS_FACE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_roll_angle",
    message0: "%{BKY_1BOT_CODEY_SENSOR_ROLL}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_ROLL_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_pitch_angle",
    message0: "%{BKY_1BOT_CODEY_SENSOR_PITCH}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_PITCH_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_rotation_angle",
    message0: "%{BKY_1BOT_CODEY_SENSOR_ROTATION}",
    args0: [
      {
        type: "field_dropdown",
        name: "AXIS",
        options: [
          ["X", "x"],
          ["Y", "y"],
          ["Z", "z"],
        ],
      },
    ],
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_ROTATION_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_reset_rotation",
    message0: "%{BKY_1BOT_CODEY_SENSOR_RESET_ROTATION}",
    args0: [
      {
        type: "field_dropdown",
        name: "AXIS",
        options: [
          ["%{BKY_1BOT_CODEY_SENSOR_ALL_AXES}", "all"],
          ["X", "x"],
          ["Y", "y"],
          ["Z", "z"],
        ],
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_RESET_ROTATION_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_timer",
    message0: "%{BKY_1BOT_CODEY_SENSOR_TIMER}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_TIMER_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_reset_timer",
    message0: "%{BKY_1BOT_CODEY_SENSOR_RESET_TIMER}",
    previousStatement: null,
    nextStatement: null,
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_RESET_TIMER_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_is_obstacle_ahead",
    message0: "%{BKY_1BOT_ROCKY_SENSOR_OBSTACLE}",
    output: "Boolean",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_ROCKY_SENSOR_OBSTACLE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_is_color",
    message0: "%{BKY_1BOT_ROCKY_SENSOR_IS_COLOR}",
    args0: [
      {
        type: "field_dropdown",
        name: "COLOR",
        options: [
          ["%{BKY_1BOT_ROCKY_COLOR_RED}", "red"],
          ["%{BKY_1BOT_ROCKY_COLOR_GREEN}", "green"],
          ["%{BKY_1BOT_ROCKY_COLOR_BLUE}", "blue"],
          ["%{BKY_1BOT_ROCKY_COLOR_YELLOW}", "yellow"],
          ["%{BKY_1BOT_ROCKY_COLOR_CYAN}", "cyan"],
          ["%{BKY_1BOT_ROCKY_COLOR_PURPLE}", "purple"],
          ["%{BKY_1BOT_ROCKY_COLOR_WHITE}", "white"],
          ["%{BKY_1BOT_ROCKY_COLOR_BLACK}", "black"],
        ],
      },
    ],
    output: "Boolean",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_ROCKY_SENSOR_IS_COLOR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_detected_color",
    message0: "%{BKY_1BOT_ROCKY_SENSOR_DETECTED_COLOR}",
    args0: [
      {
        type: "field_dropdown",
        name: "COLOR",
        options: [
          ["%{BKY_1BOT_ROCKY_COLOR_RED}", "RED"],
          ["%{BKY_1BOT_ROCKY_COLOR_GREEN}", "GREEN"],
          ["%{BKY_1BOT_ROCKY_COLOR_BLUE}", "BLUE"],
        ],
      },
    ],
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_ROCKY_SENSOR_DETECTED_COLOR_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_light_strength",
    message0: "%{BKY_1BOT_ROCKY_SENSOR_LIGHT_STRENGTH}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_ROCKY_SENSOR_LIGHT_STRENGTH_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_reflected_light",
    message0: "%{BKY_1BOT_ROCKY_SENSOR_REFLECTED_LIGHT}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_ROCKY_SENSOR_REFLECTED_LIGHT_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_reflected_infrared",
    message0: "%{BKY_1BOT_ROCKY_SENSOR_REFLECTED_INFRARED}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_ROCKY_SENSOR_REFLECTED_INFRARED_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "rocky_greyness",
    message0: "%{BKY_1BOT_ROCKY_SENSOR_GREYNESS}",
    output: "Number",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_ROCKY_SENSOR_GREYNESS_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "pulse_button",
    message0: "%{BKY_1BOT_CODEY_SENSOR_PULSE_BUTTON}",
    args0: [
      {
        type: "field_dropdown",
        name: "BUTTON",
        options: [
          ["A", "A"],
          ["B", "B"],
          ["C", "C"],
        ],
      },
    ],
    output: "Boolean",
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_PULSE_BUTTON_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_connect_rocky",
    message0: "%{BKY_1BOT_CODEY_SENSOR_CONNECT_ROCKY}",
    previousStatement: null,
    nextStatement: null,
    colour: "#4CBFE6",
    tooltip: "%{BKY_1BOT_CODEY_SENSOR_CONNECT_ROCKY_TOOLTIP}",
    helpUrl: "",
  },
];
