import { codeyNoteOptions, codeySoundOptions } from "./options";
import type { CodeyBlockDefinition } from "./types";

export const speakerBlocks: CodeyBlockDefinition[] = [
  {
    type: "codey_play_sound",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_PLAY_SOUND}",
    args0: [{ type: "field_dropdown", name: "SOUND", options: codeySoundOptions }],
    previousStatement: null,
    nextStatement: null,
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_PLAY_SOUND_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_play_sound_until_done",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_PLAY_SOUND_UNTIL_DONE}",
    args0: [{ type: "field_dropdown", name: "SOUND", options: codeySoundOptions }],
    previousStatement: null,
    nextStatement: null,
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_PLAY_SOUND_UNTIL_DONE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_stop_sounds",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_STOP_SOUNDS}",
    previousStatement: null,
    nextStatement: null,
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_STOP_SOUNDS_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_play_note",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_PLAY_NOTE}",
    args0: [
      { type: "field_dropdown", name: "NOTE", options: codeyNoteOptions },
      { type: "field_number", name: "BEAT", value: 0.25, min: 0, precision: 0.25 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_PLAY_NOTE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_rest_beat",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_REST}",
    args0: [{ type: "field_number", name: "BEAT", value: 0.25, min: 0, precision: 0.25 }],
    previousStatement: null,
    nextStatement: null,
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_REST_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_play_tone",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_PLAY_TONE}",
    args0: [
      { type: "field_number", name: "FREQUENCY", value: 700, min: 0, max: 5000, precision: 1 },
      { type: "field_number", name: "SECONDS", value: 1, min: 0, precision: 0.1 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_PLAY_TONE_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_change_volume",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_CHANGE_VOLUME}",
    args0: [{ type: "field_number", name: "DELTA", value: -10, precision: 1 }],
    previousStatement: null,
    nextStatement: null,
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_CHANGE_VOLUME_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_set_volume",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_SET_VOLUME}",
    args0: [{ type: "field_number", name: "VOLUME", value: 100, min: 0, max: 100, precision: 1 }],
    previousStatement: null,
    nextStatement: null,
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_SET_VOLUME_TOOLTIP}",
    helpUrl: "",
  },
  {
    type: "codey_current_volume",
    message0: "%{BKY_1BOT_CODEY_SPEAKER_VOLUME}",
    output: "Number",
    colour: "#C65AD9",
    tooltip: "%{BKY_1BOT_CODEY_SPEAKER_VOLUME_TOOLTIP}",
    helpUrl: "",
  },
];
