import * as Blockly from "blockly";

export function defineEsp32SensorBlocks() {
  Blockly.defineBlocksWithJsonArray([
    {
      type: "esp32_touch_read",
      message0: "%{BKY_1BOT_ESP32_SENSOR_TOUCH}",
      args0: [
        {
          type: "field_number",
          name: "PIN",
          value: 13,
          min: 0,
          max: 39,
        },
      ],
      output: "Number",
      colour: "#f39c12",
      tooltip: "Lee el valor capacitivo touch del ESP32",
      helpUrl: "",
    },
    {
      type: "esp32_ultrasonic_distance",
      message0: "%{BKY_1BOT_ESP32_SENSOR_ULTRASONIC}",
      args0: [
        {
          type: "field_number",
          name: "TRIG",
          value: 2,
          min: 0,
          max: 39,
        },
        {
          type: "field_number",
          name: "ECHO",
          value: 5,
          min: 0,
          max: 39,
        },
      ],
      output: "Number",
      colour: "#f39c12",
      tooltip: "Devuelve la distancia medida por un sensor ultrasonico",
      helpUrl: "",
    },
    {
      type: "esp32_dht_init",
      message0: "%{BKY_1BOT_ESP32_SENSOR_DHT_INIT}",
      args0: [
        {
          type: "field_number",
          name: "PIN",
          value: 4,
          min: 0,
          max: 39,
        },
        {
          type: "field_dropdown",
          name: "TYPE",
          options: [
            ["DHT11", "DHT11"],
            ["DHT22", "DHT22"],
          ],
        },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: "#f39c12",
      tooltip: "Inicializa un sensor DHT en ESP32",
      helpUrl: "",
    },
    {
      type: "esp32_dht_temperature",
      message0: "%{BKY_1BOT_ESP32_SENSOR_DHT_TEMPERATURE}",
      output: "Number",
      colour: "#f39c12",
      tooltip: "Lee la temperatura del sensor DHT",
      helpUrl: "",
    },
    {
      type: "esp32_dht_humidity",
      message0: "%{BKY_1BOT_ESP32_SENSOR_DHT_HUMIDITY}",
      output: "Number",
      colour: "#f39c12",
      tooltip: "Lee la humedad del sensor DHT",
      helpUrl: "",
    },
    {
      type: "esp32_servo_attach",
      message0: "%{BKY_1BOT_ESP32_SENSOR_SERVO_ATTACH}",
      args0: [
        {
          type: "field_number",
          name: "PIN",
          value: 18,
          min: 0,
          max: 39,
        },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: "#f39c12",
      tooltip: "Conecta un servo a un pin del ESP32",
      helpUrl: "",
    },
    {
      type: "esp32_servo_write",
      message0: "%{BKY_1BOT_ESP32_SENSOR_SERVO_WRITE}",
      args0: [
        {
          type: "field_number",
          name: "PIN",
          value: 18,
          min: 0,
          max: 39,
        },
        {
          type: "field_number",
          name: "ANGLE",
          value: 90,
          min: 0,
          max: 180,
        },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: "#f39c12",
      tooltip: "Mueve un servo a un angulo especifico",
      helpUrl: "",
    },
    {
      type: "esp32_tone_play",
      message0: "%{BKY_1BOT_ESP32_SENSOR_TONE_PLAY}",
      args0: [
        {
          type: "field_number",
          name: "PIN",
          value: 25,
          min: 0,
          max: 39,
        },
        {
          type: "field_number",
          name: "FREQUENCY",
          value: 440,
          min: 1,
        },
        {
          type: "field_number",
          name: "DURATION",
          value: 200,
          min: 1,
        },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: "#f39c12",
      tooltip: "Reproduce un tono en un buzzer",
      helpUrl: "",
    },
    {
      type: "esp32_tone_stop",
      message0: "%{BKY_1BOT_ESP32_SENSOR_TONE_STOP}",
      args0: [
        {
          type: "field_number",
          name: "PIN",
          value: 25,
          min: 0,
          max: 39,
        },
      ],
      previousStatement: null,
      nextStatement: null,
      colour: "#f39c12",
      tooltip: "Detiene el tono del buzzer",
      helpUrl: "",
    },
  ]);
}
